### ISSUE TITLE
[Bug] Can't edit table data

### ISSUE THREAD

**Issue by lbrinkmeyer81** [syd711/vpin-studio#368]
![Screenshot 2024-08-04 202741](https://github.com/user-attachments/assets/4b42aba2-d694-4b38-829a-dc0ca44b5c60)

I was able to edit table data but now I can't. I double clicked on the table, I've also right clicked on the table but it won't work. 

Suggestions?

**Comment by lbrinkmeyer81** [comment]
Also, the button at the top doesn't do anything either.

**Comment by syd711** [comment]
Thanks for reporting, I'll take a look.
If you could attach a zip with log files here, that would be great.
You can create this zip via the "Preferenes -> Submit a bug".

**Comment by syd711** [comment]
I assume this is fixed with 3.0.7

**Comment by lbrinkmeyer81** [comment]
I will check it. I still have 3.0.6. Thanks for getting those updates out so fast on this amazing piece of software. :)

**Comment by lbrinkmeyer81** [comment]
Actually, no. It didn't seem to fix it. I still can't edit table data. :(

**Comment by syd711** [comment]
Damn, I was sure that fixed the issue.
The log does not reveal anything.
The dialog does not open for all tables?
Possible workaround: try to auto-match all tables via the menu-button in the VPS section. Maybe that will fix broken data.
I will also take a look into the Popper database to see if I find anything.

**Comment by lbrinkmeyer81** [comment]
Yeah, unfortunately it doesn't work for any table at all. Thanks for looking into this. I wonder if other people are having this issue.

**Comment by lbrinkmeyer81** [comment]
I even uninstalled it and then went clear back to 3.0.4 but that one wouldn't let me either. I'm so confused.

**Comment by syd711** [comment]
I'll push out another updates this evening. I've added more logging and error handling.
This won't fix the issue but log what is actually going wrong.

**Comment by syd711** [comment]
Wanted to check back, has the issue been fixed?

**Comment by lbrinkmeyer81** [comment]
Thanks for getting back to me on this. I haven't tried lately but I will and I'll let you know for sure.

**Comment by lbrinkmeyer81** [comment]
No, unfortunately it still doesn't work. I wonder if it has a "permissions" issue or something. IDK but I appreciate you taking a look into it.

**Comment by syd711** [comment]
I only add some logging there, but with the recent version I should be able to tell what the actual error is.
If you could zip and attach the logs here, that would be great. I'm confident to find the problem in there now.

**Comment by lbrinkmeyer81** [comment]
[vpin-studio-logs.zip](https://github.com/user-attachments/files/16645670/vpin-studio-logs.zip)

Here is the files you requested. Still not working, btw. :(

**Comment by syd711** [comment]
Unfortunatelay, the zip file is corrupt. But I could read some of the UI log data and think I've found the issue.
So I assume the next update will fix your issue.

**Comment by karlsnyder0** [comment]
Here's a clean version of the zip. I also had issues reading the original zip file.
[vpin-studio-logs-clean.zip](https://github.com/user-attachments/files/16649021/vpin-studio-logs-clean.zip)

**Comment by lbrinkmeyer81** [comment]
Thank you both for the info and for the hard work that you've put in to correct this issue. I appreciate it very much, When 3.1.1 drops, I'll be sure to get it. The software itself is amazing and would be up to its full potential once you figure out what's going on with this. :)

**Comment by syd711** [comment]
I've added a fix for 3.2.0 and hope this fixes your issues.
We couldn't figure out why the actual problem happend, but tried to make the software make stable there.

**Comment by lbrinkmeyer81** [comment]
Hooray!!! 3.2.0 fixed it! Thank you so very much! You rock!

**Comment by syd711** [comment]
Awesome!
