### ISSUE TITLE
[Bug] Filter by Comment gives empty result

### ISSUE THREAD

**Issue by gorgatron1** [syd711/vpin-studio#464]
**Describe the bug**

If you filter by Comment: Any, Todo, etc. you always get an empty list of tables.

**To Reproduce**

1. Have a table with a comment
2. Use Filter -> Comments: Any

<img width="2119" alt="image" src="https://github.com/user-attachments/assets/d70f2d2f-c69f-4cb0-aa4e-00d65b72ac6d">

with filter applied:

<img width="2119" alt="image" src="https://github.com/user-attachments/assets/5bde7de3-9415-4bc4-add3-8e8c2342049b">

**Expected behavior**
Expected: a table list with that table, actual: empty list

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 15

**Comment by syd711** [comment]
Fixed with 3.5.4

**Comment by gorgatron1** [comment]
@syd711 In 3.6.0 I still see this -- in fact it look like none of the filters work:

<img width="1527" alt="image" src="https://github.com/user-attachments/assets/73c73d1f-eb32-485e-8635-f0eab03826cc">

<img width="1527" alt="image" src="https://github.com/user-attachments/assets/dc8234ca-afaf-47bb-9c57-d5f35779cad0">

This may not be new to 3.6.0, I went to use it there and noticed it again.

**Comment by syd711** [comment]
Fixed with 3.7.0
