### ISSUE TITLE
[Bug] Fix Server Performance Issues

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#703]
> Game fetch for emulator 1 took 8137ms / 1173 games / 6ms avg.

> ROM validation took 26344ms.

> 07-01 06:10:44.217 INFO  [ALTSound Loader]d.m.v.s.a.AltSoundService - Loading of 129 ALTSounds finished, took 14608ms.
07-01 06:10:46.728 INFO  [PUP Pack Scanner]d.m.v.s.p.PupPacksService - Finished PUP pack scan, found 278 packs (17103ms)
07-01 06:10:46.908 INFO  [main]d.m.v.s.g.GameService - Game fetch for emulator -1 took 16560ms / 1173 games / 14ms avg.

> Started VPinStudioServer in 46.928 seconds (JVM running for 48.579)

**Comment by spaceangel1970** [comment]
Just wondered if there has been any development with this issue..
cheers

**Comment by syd711** [comment]
Not yet. With the 3.12.4 a major problem with the general loading of tables has been fixed and we often switch to other tickets when we are in the mood for them.
I get that this one is annoying and will prioritize this.

**Comment by spaceangel1970** [comment]
Thank you for the update.

**Comment by syd711** [comment]
@spaceangel1970 
The 3.12.5 release should bring improvements regarding the speed of the server start.
Could you re-attach your vpin-studio-server.log here?

This would give me some more insights how much better the performance is now.
I'm not sure if the given changes are sufficient for general table reload.

**Comment by spaceangel1970** [comment]
I dont think much has changed, my logs are attached.
Thank You

**Comment by spaceangel1970** [comment]
[vpin-studio-logs.zip](https://github.com/user-attachments/files/18640551/vpin-studio-logs.zip)

Attached log files...

**Comment by spaceangel1970** [comment]
Sent in GitHub

**Comment by syd711** [comment]
Some stats:
- Loading of 129 ALTSounds finished, took 7842ms.
- Finished PUP pack scan, found 278 packs (10708ms)
- Game fetch for emulator -1 took 8757ms / 1180 games / 7ms avg.
- Started VPinStudioServer in 37.937 seconds (JVM running for 39.41)

The initial startup time has been reduced and also the PUP pack and ALT sound detection.
The general loading time of all tables went down to 7ms.

I think the main problem is that it still takes ~9 seconds to load all tables, right?
So a complete refresh like it is done right now can be annoying.
I'll see if I can squeeze out more.

**Comment by spaceangel1970** [comment]
Awesome, thanks for the update! Much appreciated I can update tables
directly on the cab but not remotely.

**Comment by syd711** [comment]
Not remotely? You get no connection? You use a macOS client?

**Comment by spaceangel1970** [comment]
Sorry i will explain in more detail. I am using Windows 11.
When i am on my cab everything is running ok. When i am remoting from
laptop to cab i can still do almost everything, except when i update tables
the Table Data Manager does not load and hangs with everything running
100%. At that point i have to force close Studio. It does this every time
and is not usable for this function, so i have just been working  directly
on the cab.
Hope this helps and explains things a bit better.

**Comment by syd711** [comment]
It does indeed wasn't aware of this.
I'll take a look.

**Comment by syd711** [comment]
I could reproduce this.
The issue should be fixed with the next release.

**Comment by spaceangel1970** [comment]
Sorry to report the new update did not fix my issue, i have attached logs for your reference.
Cheers.


[vpin-studio-logs.zip](https://github.com/user-attachments/files/18701999/vpin-studio-logs.zip)

ce

**Comment by syd711** [comment]
Mmh, sorry to hear that. I tried remote connect but only have a Win laptop on my hand.
The 3.12.7 patch I deployed today should provide more logging to tackle this problem.
The main issue is, that there seems to be one request to the server that block everything and because it blocks, the actual call is not logged 'cos it never finishes.

I will also ask another developer of us who owns a mac if he can reproduce this.

**Comment by gonzonia** [comment]
@spaceangel1970 I'd like to look into this. I want to make sure I have the details correct.

**Server/Cabinet**
Windows 11
Vpin-Studio version?

**Remote Laptop Client**
Mac OS?
Vpin-Studio version?

Thanks.

**Comment by spaceangel1970** [comment]
No, it's not.
i don't have Mac OS mine is win11 on both.

**Comment by spaceangel1970** [comment]
I have updated to Version 3.12.7 and attached the log files.

[vpin-studio-logs.zip](https://github.com/user-attachments/files/18714384/vpin-studio-logs.zip)

**Comment by gonzonia** [comment]
Can you upload the log from the client too? It should be in the file where the app was installed. 
I see an error in the ui-logs but that's from Feb. 1 and 3.12.6

**Comment by spaceangel1970** [comment]
Yes, I can, please find the files attached.
Thank You.

**Comment by gonzonia** [comment]
Unfortunately, it didn't come through with the email. Please upload it to Github.

**Comment by spaceangel1970** [comment]
I will resend it.

**Comment by spaceangel1970** [comment]
resent log files attached

[VPin-Studio-logs.zip](https://github.com/user-attachments/files/18716521/VPin-Studio-logs.zip)

**Comment by syd711** [comment]
Sorry for the confusion guys! I catched a cold and was a bit under the weather yesterday, mixing up this ticket with another one.

@gonzonia I'll ping you about the actual issue I wanted to ask your help for.
@spaceangel1970 I'll continue to look into this.

**Comment by spaceangel1970** [comment]
No worries, thanks for the update!

**Comment by syd711** [comment]
So to narrow down what is broken exactly I created a new Client where the Table Data Dialog does not load all data.
This way, I can pin down what requests might possible the cause for the Studio client to stall. I hope you have the patience for that ;)

You can download 

https://www.dropbox.com/scl/fi/z4e0w49tn4w9wv759wlqu/VPin-Studio.zip?rlkey=usxyqpv1yjpznjuhgoiknfi2s&st=qylj07ie&dl=1

and replace the existing VPin-Studio.exe with it.
I assume the Table Dialog will open the from the remote client, but some tabs will be missing.

This test client is compatible to the latest release, so you really only have to exchange this file on your remote laptop, no changes on the cabinet required.

**Comment by spaceangel1970** [comment]
ok i will give it a try and report back soon.

**Comment by spaceangel1970** [comment]
Please find attached log files from cab and client i didnt know which one was required.

[VPin-Studio-Cab.zip](https://github.com/user-attachments/files/18726608/VPin-Studio-Cab.zip)
[VPin-Studio-Client.zip](https://github.com/user-attachments/files/18726607/VPin-Studio-Client.zip)

**Comment by syd711** [comment]
Thanks, I am narrowing it down. Here comes the next attempt: 

https://www.dropbox.com/scl/fi/93i9clchn7hqlobyg6uv5/VPin-Studio.zip?rlkey=wcjc0wjkjubslkkk6ylx1t5nr&st=ym6ji98i&dl=1

**Comment by spaceangel1970** [comment]
No problem I'll run it and get back to you.

**Comment by spaceangel1970** [comment]
Please find attached Cab and Client logs for the latest Debug attempt.
Cheers.

[VPin-Studio-cab.zip](https://github.com/user-attachments/files/18741751/VPin-Studio-cab.zip)
[VPin-Studio-client.zip](https://github.com/user-attachments/files/18741752/VPin-Studio-client.zip)

**Comment by syd711** [comment]
Ok, no errors in the log. But did the table data dialog open now? Is the client still crashing?

**Comment by spaceangel1970** [comment]
Yes table data opened with both versions of studio you sent me.

**Comment by spaceangel1970** [comment]
And didn't crash.

**Comment by syd711** [comment]
Ok so, the crashing is caused by one of these 4x tabs:
- Screens Tab
- Score Data Tab
- Auto Renaming Panel
- PinVOL Settings Tab

I have created a version now where only the **PinVOL** tab is disabled. For some reason I assume that's the "bad guy".

https://www.dropbox.com/scl/fi/qjnk0ojkbc08xvsxkp01o/VPin-Studio.zip?rlkey=u1uu3ddt2zkfnjyuj0wf5h035&st=4zsyyjzr&dl=1

Please let me know if the version crashes or not.

**Comment by spaceangel1970** [comment]
Ok, I'll check it out.

**Comment by spaceangel1970** [comment]
That worked no crashes, table data dialog opened everyime.

**Comment by syd711** [comment]
Alright, so we are getting close. 

Here is the "regular" version now again:
https://www.dropbox.com/scl/fi/gmjqapp2swioarzo7v2rk/VPin-Studio.zip?rlkey=vd7gou2g3fiqrzsvrlci72eq0&st=q2vy9dt6&dl=1

If the issue wasn't fixed by accident, the dialog should block/crash again.
I assume the issue is something inside the configuration files of PinVOL which is not handled properly by the Studio.

Could you attach all PinVol****.ini files located in the **resources** folder of VPin Studio server here?

**Comment by spaceangel1970** [comment]
Studio is crashing again and not loading Table Manager, The PinVol files are attached from the cabinet.
There are no PinVol.ini files on the client so i presume these are the ones.

[PinVol-Cabinet.zip](https://github.com/user-attachments/files/18764565/PinVol-Cabinet.zip)

**Comment by syd711** [comment]
Thanks, now  that I know the root cause, I hope to deliver a patch soon.

**Comment by spaceangel1970** [comment]
No problem thanks for your patience.

**Comment by syd711** [comment]
I found the cause for the crash.
The PinVolTables.ini file is 300MB large. I think I have messed up the file and need to re-visit how this can happen.
In the meantime, just delete the PinVolTables.ini.

I'm sorry having messed up your config there. The file has ~500.000 entries there, so simply deleting it is the best way to go.
I'll provide a fix with the next version, so that this can't happen again.

**Comment by spaceangel1970** [comment]
No worries, thanks for the update!

**Comment by spaceangel1970** [comment]
I deleted the ini file and that fixed the problem. I will test it more
tomorrow thanks for your help.

**Comment by syd711** [comment]
Thanks for your patience here again!

**Comment by syd711** [comment]
I consider the issue as fixed, the patch was delivered with  3.12.9.
